#!/bin/bash

# 检测是否在 tmux 会话中
if [[ -z "$TMUX" ]]; then
    # 如果不在 tmux 会话中，创建一个名为 ide 的 session，确保工作目录为当前目录，并创建三个 window
    tmux new-session -d -s ide -c "$PWD" -n editor # 创建第一个 window，命名为 editor
    tmux new-window -t ide:2 -n terminal -c "$PWD" # 创建第二个 window，命名为 terminal
    tmux new-window -t ide:3 -n logs -c "$PWD"     # 创建第三个 window，命名为 logs

    # 切换到第一个 window 并连接到 ide session
    tmux select-window -t ide:1
    tmux attach -t ide
else
    # 如果已经在 tmux 会话中，则在当前 session 创建三个 window，并确保工作目录为当前目录
    tmux new-window -n editor -c "$PWD"   # 创建第一个 window，命名为 editor
    tmux new-window -n terminal -c "$PWD" # 创建第二个 window，命名为 terminal
    tmux new-window -n logs -c "$PWD"     # 创建第三个 window，命名为 logs

    # 切换到第一个 window
    tmux select-window -t 1
fi
